### ISSUE TITLE
Integration of Dark Kitchens into the Porto Places

### ISSUE THREAD

**Issue by letier3110** [letier3110/porto-places#3]
#### Description:
The concept of "Dark Kitchens," also known as ghost kitchens or cloud kitchens, presents a unique challenge for our current venue display system. Unlike traditional dining venues, dark kitchens do not have a physical space for customers to dine in or even visit. They primarily operate as delivery-only services, often functioning from non-disclosed locations. As our current project displays venues with tables or ordering places and dining areas, it becomes crucial to adapt our system to include dark kitchens effectively.

#### Current System:
- **Venues with tables or ordering places:** These are displayed either as a list or as POIs (Points of Interest) on an interactive map.
- **Interactive Map:** Shows the physical locations of venues where customers can dine in or pick up orders.

#### Challenges:
1. **No Physical Dining Space:** Dark kitchens do not have a seating area or a customer-facing order counter.
2. **Non-Disclosed Locations:** The exact location of dark kitchens is often not shared with the public for business strategy reasons.
3. **Delivery-Only Model:** These kitchens cater exclusively to online orders and deliveries, requiring a different approach to how they are presented in the system.

#### Proposed Solutions:
1. **Virtual Representation:**
   - Introduce a new category or marker for dark kitchens on the interactive map that indicates their presence without disclosing the exact location.
   - Use an icon or color code that differentiates dark kitchens from traditional dining venues.

2. **Service Area Mapping:**
   - Instead of showing a precise location, display the delivery service area of each dark kitchen. This can be represented as a shaded region on the map.
   - Provide information about the delivery zones covered by each dark kitchen, allowing users to understand if they can order from these kitchens.

3. **Enhanced Listing Information:**
   - Add a filter option in the venue list to sort or highlight dark kitchens separately.
   - Include detailed descriptions, menus, and delivery options for dark kitchens in their listings.

4. **Integration with Delivery Services:**
   - Collaborate with food delivery services to pull in real-time data about available dark kitchens and their menus.
   - Provide direct links or integration for placing orders through popular delivery platforms.

5. **User Notifications:**
   - Implement a notification system that alerts users when new dark kitchens become available in their area.
   - Allow users to subscribe to updates from specific dark kitchens or types of cuisine.

#### Benefits:
- **Inclusivity:** Ensuring that dark kitchens are represented in the system makes our project more comprehensive and user-friendly.
- **User Convenience:** Users can discover and order from dark kitchens easily, enhancing their overall experience.
- **Market Adaptation:** Adapting to the growing trend of dark kitchens helps keep the project relevant and competitive.

**Comment by letier3110** [comment]
issue is generated by LLM. The possible solution is just hide this venues from map view, but place them into the list. Maybe add specific "dark kitchen" tag or label "virtual" to the card.

**Comment by bob3x255** [comment]
@letier3110 I am confused. 
Why do we need dark kitchens? What value will it serve to the end-user? There are delivery apps for that.

**Comment by letier3110** [comment]
virtual venues then. I'll close this issue becuse of the vision of this service as "nice places to visit" and not "services are available in Porto"
