### ISSUE TITLE
Integration of Social Media Businesses into the Porto Places

### ISSUE THREAD

**Issue by letier3110** [letier3110/porto-places#4]
#### Description:
The emergence of "Social Media Businesses" in the food and beverage industry presents a new set of challenges for our venue display system. These businesses operate primarily through social media platforms such as Instagram, Facebook, and Telegram, and often do not have a fixed physical location or a Google Maps link. Instead, they rely on their social media presence to reach customers, share menus, and take orders. As our current system is designed to display venues with physical dining places linked to Google Maps, we need to adapt our approach to include and effectively present social media businesses.

#### Current System:
- **Physical Venues:** These are displayed with links to Google Maps and information about their physical dining spaces.
- **Interactive Map:** Shows the physical locations of venues where customers can dine in or pick up orders.

#### Challenges:
1. **No Fixed Location:** Social media businesses often operate from various locations, making it difficult to pin them on a map.
2. **Lack of Google Maps Link:** These businesses do not have a consistent or official Google Maps presence.
3. **Social Media Integration:** They rely on social media platforms for customer interaction, order placement, and marketing.

#### Proposed Solutions:
1. **Virtual Representation:**
   - Introduce a new category or marker for social media businesses on the interactive map that indicates their presence without a specific location.
   - Use an icon or color code that differentiates social media businesses from traditional dining venues.

2. **Social Media Links:**
   - Allow venues to include links to their Instagram accounts, Facebook groups, Telegram channels, and custom websites in their listings.
   - Display these links prominently in the venue details, enabling users to easily access and follow these businesses on social media.

3. **Enhanced Listing Information:**
   - Add a filter option in the venue list to sort or highlight social media businesses separately.
   - Include detailed descriptions, social media links, sample menus, and ordering instructions in their listings.

4. **Service Area Mapping (if applicable):**
   - If the social media business offers delivery, display the delivery service area as a shaded region on the map.
   - Provide information about the delivery zones covered by each social media business.

5. **User Notifications:**
   - Implement a notification system that alerts users when new social media businesses become available in their area.
   - Allow users to subscribe to updates from specific social media businesses or types of cuisine.

6. **Social Media Feeds:**
   - Integrate social media feeds directly into the venue details page, allowing users to see recent posts, updates, and promotions from the business.
   - Use APIs from social media platforms to pull real-time content.

#### Benefits:
- **Inclusivity:** Ensuring that social media businesses are represented in the system makes our project more comprehensive and user-friendly.
- **User Convenience:** Users can discover and interact with social media businesses easily, enhancing their overall experience.
- **Market Adaptation:** Adapting to the growing trend of social media businesses helps keep the project relevant and competitive.
- **Enhanced User Engagement:** Integrating social media feeds and notifications keeps users engaged and informed about their favorite venues.

**Comment by letier3110** [comment]
issue is generated by LLM. The possible solution is just hide this venues from map view and add into description contacts to specific social media / phone numbers / etc

**Comment by bob3x255** [comment]
@letier3110 
Same as in #3 . I don't understand WHY.
I see a possibility how we can adapt that - pop-up events. 
Although it will require a lot of moderation and regular research. So, I'd stick to a simple plan right now.

**Comment by letier3110** [comment]
I'll add a social media links and embed preview in full description of the venue
