### ISSUE TITLE
Suggestion: decide on the modes (categories) that we have and stick to them

### ISSUE THREAD

**Issue by bob3x255** [letier3110/porto-places#6]
As of now we have:
- Food+Drink
- Climbing
- Geek 🎮
- Work 💼
- Clubs 🎤

I suggest:
- Food+Drink (obviously! and I'd further break it down actually but later)
- Sports (climbing, outdoor gyms, some good gyms)
- Geek (just yes, )
- Work (remove this as the mode, people can just google co-working spaces, instead we can add a tag ["laptop friendly"] or something)
- Spots (places where people can hagout - parks, sunset views just good parks etc)

**Comment by bob3x255** [comment]
@letier3110 see commits in the branch. 

Before I proceed, let's agree on what we do with work and clubs?

**Comment by letier3110** [comment]
we can move them to spots
